/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import Repository.HoaDonBanRepository;
import Service.Impl.HoaDonBanImpl;
import Services.HoaDonBanService;
import ViewModel.CTHDBanViewModel;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trung
 */
public class CTHoaDonBan extends javax.swing.JFrame {

    DefaultTableModel model;
    int row;
    List<CTHDBanViewModel> list;
    HoaDonBanService banService;
    int id;
Locale lc = new Locale("nv", "VN");
    NumberFormat nf = NumberFormat.getInstance(lc);
    /**
     * Creates new form Camera
     */
    public CTHoaDonBan(int id, DefaultTableModel model, int row) {
        initComponents();
        this.model = model;
        this.row = row;
        this.id = id;
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        banService = new HoaDonBanImpl();
        fillTable(id);
    }

    public void fillTable(int id) {
        DefaultTableModel model = (DefaultTableModel) table011.getModel();
        model.setRowCount(0);
        list = banService.selectByIdBan(id);
        for (CTHDBanViewModel d : list) {
            model.addRow(new Object[]{
                d.getIdCTHoaDonBan(),
                d.getSoImei(),
                d.getTenSanPham(),
                d.getDanhMuc(),
                d.getDungLuong(),
                d.getMauSac(),
                d.getTenKhachHang(),
//                d.getMaGiamGia(),
                nf.format( d.getTONGTIEN() )+ " đ",
                nf.format(d.getTONGCONGTIENPHAITRA()) + " đ",
                nf.format(d.getTIENVOUCHER()) + " đ",
                nf.format(d.getTIENKHACHDUA()) + " đ",
                nf.format(d.getTIENTRALAI()) + " đ"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table011 = new chucNang.Table01();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hóa Đơn Chi Tiết");

        table011.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã Imei", "Tên SP", "Danh Mục", "Dung Lượng", "Màu Sắc", "Tên KH", "Tổng Tiền", "Tiền phải trả", "Tiền Voucher", "Tiền khách đưa", "Tiền trả lại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table011);
        if (table011.getColumnModel().getColumnCount() > 0) {
            table011.getColumnModel().getColumn(0).setResizable(false);
            table011.getColumnModel().getColumn(1).setResizable(false);
            table011.getColumnModel().getColumn(2).setResizable(false);
            table011.getColumnModel().getColumn(3).setResizable(false);
            table011.getColumnModel().getColumn(4).setResizable(false);
            table011.getColumnModel().getColumn(5).setResizable(false);
            table011.getColumnModel().getColumn(6).setResizable(false);
            table011.getColumnModel().getColumn(7).setResizable(false);
            table011.getColumnModel().getColumn(8).setResizable(false);
            table011.getColumnModel().getColumn(9).setResizable(false);
            table011.getColumnModel().getColumn(10).setResizable(false);
            table011.getColumnModel().getColumn(11).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private chucNang.Table01 table011;
    // End of variables declaration//GEN-END:variables
}
