/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.form;

import Repository.ThongKeDoanhThuRepository;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.duan.swing.Excel;

/**
 *
 * @author ADMIN
 */
public class DoanhThu extends javax.swing.JPanel {

    DefaultTableModel tbl_model = new DefaultTableModel();
    ThongKeDoanhThuRepository rep = new ThongKeDoanhThuRepository();
    
    public DoanhThu() {
        initComponents();
        fillYear();
         rdo_bieudoduong.setSelected(true);
        for (int i = 0; i < tbl_thongkedoanhso.getRowCount(); i++) {
            tbl_thongkedoanhso.setValueAt(nf.format(tbl_thongkedoanhso.getValueAt(i, 2)) + " đ", i, 2);
            tbl_thongkedoanhso.setValueAt(nf.format(tbl_thongkedoanhso.getValueAt(i, 3)) + " đ", i, 3);
            tbl_thongkedoanhso.setValueAt(nf.format(tbl_thongkedoanhso.getValueAt(i, 4)) + " đ", i, 4);
            tbl_thongkedoanhso.setValueAt(nf.format(tbl_thongkedoanhso.getValueAt(i, 5)) + " đ", i, 5);
        }
    }
     Locale lc = new Locale("nv", "VN");
    NumberFormat nf = NumberFormat.getInstance(lc);
    
 public void fillYear() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_nam.getModel();
        model.removeAllElements();
        List<Integer> list = rep.selectYears();
        for (Integer i : list) {
            model.addElement(i);
        }
    }
 public String deleteLastKey(String str) {
        if (str.charAt(str.length() - 1) == 'đ') {
            str = str.replace(str.substring(str.length() - 1), "");
            return str;
        } else {
            return str;
        }
    }
      public String fomartFloat(String txt) {
        String pattern = deleteLastKey(txt);
        return pattern = pattern.replaceAll(",", "");
    }
      public void fillTable() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tbl_thongkedoanhso.getModel();
        model.setRowCount(0);
        int year = (int) cbo_nam.getSelectedItem();
        List<Object[]> list = rep.getSalesStatisticalRevenue(year);
        for (Object[] o : list) {  
            model.addRow(o);
        }
        for (int i = 0; i < tbl_thongkedoanhso.getRowCount(); i++) {
           // int moneyImport = rep.getSelectImport((int) tbl_thongkedoanhso.getValueAt(i, 0), (int) cbo_nam.getSelectedItem());
            int giaNhap = (int) tbl_thongkedoanhso.getValueAt(i, 3);
            int tongGiaKhuyenMai = (int) tbl_thongkedoanhso.getValueAt(i, 4);
            tbl_thongkedoanhso.setValueAt(giaNhap, i, 3);
            tbl_thongkedoanhso.setValueAt(tongGiaKhuyenMai, i, 4);
            tbl_thongkedoanhso.setValueAt((int) tbl_thongkedoanhso.getValueAt(i, 2) - (giaNhap + tongGiaKhuyenMai), i, 5);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbo_nam = new chucNang.Combobox();
        rdo_bieudoduong = new chucNang.RadioButtonCustom();
        rdo_bieudocot = new chucNang.RadioButtonCustom();
        btn_bieudo = new chucNang.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongkedoanhso = new chucNang.Table01();
        myButton2 = new chucNang.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thống Kê Doanh Thu");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cbo_nam.setLabeText("Năm");
        cbo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_namActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdo_bieudoduong);
        rdo_bieudoduong.setText("Biểu Đồ Đường ");

        buttonGroup1.add(rdo_bieudocot);
        rdo_bieudocot.setText("Biểu Đồ Cột");

        btn_bieudo.setText("Biểu Đồ");
        btn_bieudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bieudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo_bieudoduong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdo_bieudocot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cbo_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(rdo_bieudoduong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdo_bieudocot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_bieudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_thongkedoanhso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Sản Phẩm Đã Bán", "Tổng Giá Bán", "Tổng Giá Nhập", "Tổng Giá Khuyến Mãi", "Lợi Nhuận"
            }
        ));
        jScrollPane1.setViewportView(tbl_thongkedoanhso);

        myButton2.setText("Xuất");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_namActionPerformed
        // TODO add your handling code here:
        try {
            fillTable();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cbo_namActionPerformed

    private void btn_bieudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bieudoActionPerformed
        // TODO add your handling code here:
        if (rdo_bieudoduong.isSelected()) {
            new BieuDoDuong((DefaultTableModel) tbl_thongkedoanhso.getModel(),null).setVisible(true);
        
        } else {
            new BieuDoCot((DefaultTableModel) tbl_thongkedoanhso.getModel()).setVisible(true);
        }
    }//GEN-LAST:event_btn_bieudoActionPerformed

public void excelSell() throws IOException {
        Excel.outExcel((DefaultTableModel) tbl_thongkedoanhso.getModel());
       JOptionPane.showMessageDialog(this,"Xuất file thành công");
    }
    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        try {
            excelSell();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_myButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chucNang.MyButton btn_bieudo;
    private javax.swing.ButtonGroup buttonGroup1;
    private chucNang.Combobox cbo_nam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private chucNang.MyButton myButton2;
    private chucNang.RadioButtonCustom rdo_bieudocot;
    private chucNang.RadioButtonCustom rdo_bieudoduong;
    private chucNang.Table01 tbl_thongkedoanhso;
    // End of variables declaration//GEN-END:variables
}
