/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.logiin;

import DomainModel.TaiKhoan;
import DomainModel.Users;
import Service.Impl.TaiKhoanImpl;
import Service.Impl.UsersImpl;
import Services.TaiKhoanService;
import Services.UsersService;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import view.trangchu.trangchu;

/**
 *
 * @author ADMIN
 */
public class DangNhap extends javax.swing.JPanel {

    TaiKhoanService taiKhoanService = new TaiKhoanImpl();
    UsersService userService = new UsersImpl();
    List<Users> listUser = new ArrayList<>();
    List<TaiKhoan> listTaiKhoan = new ArrayList<>();
    
    public DangNhap() {
        initComponents();
        txt_users.grabFocus();
    }
    public boolean login() {
        String userName = txt_users.getText();
        String passWord = new String(txt_PassWord.getPassword());
        try {          
            TaiKhoan taikhoan = taiKhoanService.getTaiKhoan(userName);
            if (taikhoan == null) {    //nếu user sai
                JOptionPane.showMessageDialog(this,"Sai Tên Đăng Nhập");
                return false;
            } else {
                String  passwordSystem = taikhoan.getMatKhau();
                if (passWord.equalsIgnoreCase(passwordSystem)) {
                    JOptionPane.showMessageDialog(this,"Đăng Nhập Thành Công");
                    Users users=  userService.getUsers(taikhoan.getIdUsers());
                    System.out.println(taikhoan.getIdUsers());
                    Auth.user = users;
                    new trangchu().setVisible(true);
                    this.setVisible(false);
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this,"Sai Mật Khẩu Rồi Bạn Ơi! ");
                    return false;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Lỗi Truy Vấn Dữ Liệu");
        }
        return true;

    }
    public void backLogin() {
       txt_users.grabFocus();
    }
public void addEventQuenMatKhau(ActionListener event){
    btn_quenMatKHau.addActionListener(event);
}
public void addEventDangNhap(ActionListener event){
    btn_DangNhap.addActionListener(event);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_users = new view.logiin.txtField();
        txt_PassWord = new view.logiin.password();
        btn_DangNhap = new view.logiin.button();
        btn_quenMatKHau = new view.logiin.button();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txt_users.setText("admin");
        txt_users.setToolTipText("");
        txt_users.setHint("USERNAME");
        txt_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usersActionPerformed(evt);
            }
        });

        txt_PassWord.setText("123456");
        txt_PassWord.setHint("PASSWORD");
        txt_PassWord.setName(""); // NOI18N
        txt_PassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PassWordActionPerformed(evt);
            }
        });

        btn_DangNhap.setBackground(new java.awt.Color(104, 159, 158));
        btn_DangNhap.setText("Đăng Nhập");
        btn_DangNhap.setToolTipText("");
        btn_DangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        btn_quenMatKHau.setBackground(new java.awt.Color(255, 255, 255));
        btn_quenMatKHau.setText("Quên Mật Khẩu");
        btn_quenMatKHau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Đăng Nhập");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_quenMatKHau, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_quenMatKHau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usersActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void txt_PassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PassWordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.logiin.button btn_DangNhap;
    private view.logiin.button btn_quenMatKHau;
    private javax.swing.JLabel jLabel1;
    private view.logiin.password txt_PassWord;
    private view.logiin.txtField txt_users;
    // End of variables declaration//GEN-END:variables

    
}
